<?php 
/*
IMPLEMENTAR CLASSE VIDEO
	ATRIBUTOS PRIVADOS
		TITULO
		AVALIAÇÃO
		VIEWS
		CURSTIDAS
		REPRODUZINDO
	INTERFACE QUE É IMPLEMENTADA - CHAMADA ACOES VIDEO
		METODOS PRIVADOS
			PLAY()
			PAUSE()
			LIKE()
	CLASSE GAFANHOTO
		PRIVADO ATRIBUTO LOGIN
		PRIVADO ATRIBUTO TOTASSISTIDO
		METODO PUBLICO VIUU MAIS UM()
	CLASSE ABSTRATA MAE DE GAFANHOTO - PESSOA
		ATRIBUTOS PROTEGIDOS
			NOME
			IDADE
			SEXO
			EXPERIENCI
		METODOS PROTEGIDOS
			GANHAReXP()
*/
/* INTERFACE ACOES VIDEOS
	INTERFACE ACOES VIDOES
		METODOS PRIVADOS
			PLAY()
			PAUSE()
			LIKE()
*/
/*
	CLASSE VIDEO IMPELEMNTS ACOES VIDEO
		PRIVADOS TITULO, AVALIAÇÃO, VIEWS, CURTIDAS, REPORDUZINDO

	METODOS DA INTERFACE
		PLAY()
			SE REPRODUZINDO FALSO
				SET REPRODUZINDO(TRUE)
			ELSE
				ESCREVE VIDEO JÁ ESTA SENDO REPRODUZIDO
		PAUSE()
			SE REPRODUZINDO FALSE
				ECHO PAUSANDO O VIDEO
				SET REPRODUZINDO(FALSE)
			ELSE
				ESCREVER VIDEO NÃO ESTA SENDO REPRODUZIDO
		LIKE()
			VAI TER A VER COM A AVALIAÇÃO

	METODOS ESPECIAIS
		CONSTRUCT
			TITULO
			REPRODUZINDO PARA FALSO
		GETTERS
			GET TITULO
				RETURNA THIS TITULO
			GET AVALIACAO
				RETORNA THIS AVALIACAO
			GET VIEWS
				RETORNA THIS VIEWS
			GET CURTIDAS
				RETORNA THIS CURTIDAS
			GET REPRODUZINDO
				RETORNA THIS REPRODUZINDO
		SETTERS
			SET TITULO ($TITULO)
				THIS TITULO = $TITULO
			SET AVALIACAO ($ AVALIACAO)
				THIS AVALIACAO = $AVALIACAO
			SET VIEWS ()	
				THIS VIEWS += 1
			SET CURTIDAS ()
				THIS CURTIDAS += 1
			SET REPRODUZINDO ($ REPRODUZINDO)
				THIS REPRODUZINDO = $REPRODUZINDO
*/
/* 
	CLASSE GAFANHOTO ESTENDE PESSOA
		PRIVADO ATRIBUTO LOGIN
		PRIVADO ATRIBUTO TOTASSISTIDO

		CONSTRUCT
			SET LOGIN ($LOGIN)
			SET SENHA ($SENHA)
			ECHO USUARIO CRIADO COM SUCESSO
		GET LOGIN
			
		GET SENHA

		SET SENHA

		SET LOGIN

		METODO PUBLICO VIUU MAIS UM()

*/
/*
	CLASSE ABSTRATA PESSOA
		PROTECTED NOME, SEXO, IDADE, EXPERIENCIA

		METODO PROTEGIDO
			ABSTRATO GANHAR EXPERIENCIA()
		GETTERS
			GET NOME
			GET IDADE
			GET SEXO
			GET EXPERIENCIA
		SETTER
			SET NOME
			SET SEXO
			SET IDADE
			SET EXPERIENCIA
		CONSTRUCT
			SET NOME($NOME)
			SET SEXO ($SEXO)
			SET IDADE ($IDADE)
			THIS EXPERIENCIA = 0

*/

/* CLASSE VISUALIZAÇÃO
		ATRIBUTOS PRIVADOS
			ESPECTADOR
			FILE
		METODOS PUBLICOS
			AVALIAR()
			AVALIAR(NOTA)
			AVALIAR(PORC)

COLOCA GAFANHOTO E VIDEO COM REQUIRE
	CLASSE VISUALIZACO

		PRIVATE ESPECTADOR, FILME
		
		CONSTRUCT ($FILME, $ESPECTADOR)
			SET FILME($FILME)
			$THIS SET ESPECTADOR ($ESPECTADOR)
		GETTERS E SETTERS
			SET FILME ($FILME)
				THIS FILME = $FILME
			SET ESPECTADOR( $ESPECTADOR)
				THIS ESPECTADOR = $EPECTADOR
		AVALIAR
			THIS SETCURTIDAS()
		AVALIARNOTA($NOTA)

		AVALIARPORCE($PORCENTAGEM)


*/ ?>