<?php 
/*
CLASSE PESSOA - RECEBE COISAS EM COMUM DAS DEMAIS - ESSA SENDO A CLASSE MÃE
	ATRIBUTOS
		NOME
		IDADE
		SEXO
	METODOS
		FAZER ANIVERSARIO

CLASSE ALUNO
	ATRIBUTOS
		MATRICULA
		CURSO
	METODOS
		CANCELAR MATRICULA

CLASSE FUNCIONARIO
	METODOS
		SETOR
		TRABALHANDO
	METODOS
		MUDAR TRABALHO

CLASSE PROFESSOR
	ATRIBUTOS
		ESPECIALIDADE
		SALARIO
	METODOS
		RECEBER AUMENTO
	
*/
// CRIAR NO INDEX QUATRO OBJETOS DE CADA CLASSE COM P1...ATE 4
// UTILIZAR OS METODOS NOS OBJETOS

//////////////////////////////////////////////////////////////////////////////////

//HERANÇA PARTE 2 - NAVEGAÇÃO PELA HERANÇA
	/*
	CLASSE ABSTRATA PESSOA
		NOME
		SEXO
		IDADE
		FAZER ANIVERSARIO()

	TODAS ESSAS HERDAM DO PROFESSOR PQ SÃO FILHAS DA CLASSE
	CLASSE VISITANTE
	CLASSE ALUNO 
		MATR
		CURSO
		PAGAR MENSALIDADE
			//ESCREVER PAGAR MENSALIDADE
	CLASSE PROFESSOR
		ESPECIALIDADE
		SALARIO
		RECEBR AUMENTO
	DUAS ESPECIALIZAÇÕES DE ALUNO
		CLASSE TECNICO
			REGISTRO PROFISSIONAL
			PRATICAR()
				ESCREVER PRATICANDO
		CLASSE BOLSISTA
			BOLSA
			RENOVAR BOLSA()
				ESCREVER RENOVAÇÃO DE BOLSA
			PAGARMENSALIDADE() - SOBREESCREVENDO METODOS ANTERIOR
				ESCRVER PAGANDO MENSALIDADE COM DESCONTO

	*/

//ABSTRATO E FINAL
		//ABSTRATO
			//METODO - DECLARADO MAS NAO IMPLEMENTSADO - SOMENTE DENTRO DE INTERFACE OU CALSSE ABSTRATA
			//CLASSE - SO PODE SER PROGENITORA NAO PODE SER INSTANCIADA
		//FINAL
			//METODO - NAO PODE SER SUBSCRITO E É OBRIGATORIAMENTE HERDADO
			//CLASSE - NAO PODE SER HERDADE POR OUTRA - NAO PODE TER FILHO SENDO ASSIM UMA FOLHA - ESTERIL

?>