<?php 
/*
POLIMORFISMO PARTE 1
	POLIMORFISMO - QUANTIDADE E TIPO DOS PARAMETROS IGUAIS

SOBREPOSIÇÃO
	CLASSE ABSTRATA MAE ANIMAL
		PROTECTED PESO
		 '' IDADE
		 '' MEMBROS
		ABSTRATO LOCOMOVER()
		ABSTRATO ALIMENTAR()
		ABSTRATO EMITIRSOM()

CLASSES FILHAS
	CLASSE MAMIFERO
		CORPELO
		LOCOMOVER()
			ESCREVER CORRENDO
		ALIMENTAR()
			ESCREVER COMENDO VEGETAIS OU CARNE
		EMITIRSOM()

	CLASSE REPTIL
		CORESCAMA
		LOCOMOVER()
			ESCREVER ANDANDO
		ALIMENTAR()
			ESCEVER COMENDO VEGETAIS E INSETOS
		EMITIRSOM()
	CLASSE PEIXE
		CORESCAMA
		SOLTARBOLHA()
			ESCREVER BLU BLU BLU
		LOCOMOVER()
			ESCREVER NADANDO
		ALIMENTAR()
			ESCREVER COMENDO SUBSTANCIAS
		EMITIRSOM()
			ESCREVER NAO FAZ SOM
	CLASSE AVE
		CORPENA
		FAZERNINHO()
			ESCREVER FAZENDO NINHO
		LOCOMOVER()
			ESCREVER VOAR
		ALIMENTAR()
			ESCREVR COMER INSTETOS OU PEQUENOS ANIMAIS
		EMITIRSOM()
			ESCREVER PIAR

CLASSES DE ANIMAIS SENDO FILHAS DAS FILHAS DE ANIMAL CADA QUAL EM SEU TIPO
	CLASSE CANGURU estende mamifero
		locomover()
			escreve saltar
		alimentar()
			escreve comendo frutas e folhas
		emitir som()
			escreve nao sei
		usar bolsa()
			escreve carregando algo na bolsa

	CLASSE DOG MAMIFERO
		EMITIR SOM()
			LATIR
		ALIMENTAR()
			COMENDO RAÇÃO
		BRINCAR()
			PEGANDO BOLA
		ABANAR RABO
			MEXER RABINHO

	CLASSE COBRA REPTIL
		LOCOMOVER()
			ESCREVE RASTEJAR
		EMITR SOM()
			ESCREVE SSSSSHHHHH
		ALIMENTAR()
			ESCREVE COMENDO PEQUENOS ANIMAIS
		TROCAR PELE()
			ESCREVE TROCANDO DE PELE

	CLASSE TARTARUGA REPTIL
		LOCOMOVER()
			ESCREVE ANDANDO BEEEEEM DEVAGAR
		EMITIR SOM()
			ESCREVE SOM DA TARTARUGA
		ALIMENTAR()
			COMNEDO FOLHAS/VEGETAIS OU FRUTAS BEEEM DEVAGAR
		ESCONDER()
			ESCREVER ENTRANDO DENTRO DO CASCO

	CLASS PEIXE PALHACO PEIXE
		
	CLASS ARARA AVE
		EMITIR SOM()
			ESCREVE ARARA ARARA ARARA

*/
/* POLIMORFISMO PARTE 2

SOBRECARGA - PHP NÃO SUPORTA ESTE TIPO - SOLUÇÃO NOMES DIFERENTES DE METODOS
	MANTENDO ANIMAL - MAMIFERO
		CRIAR CLASSE LOBO ESTENDENDO MAMIFERO
			SOBREPOR EMITIR SOM PARA O UIVO
		CLASSE CAHCORRO ESTENDE LOBO
			SOPREBOR EMITIR SOM PARA CACHURO COM LATIDO

			METODO REAGIR
				DEPENDENDO DA FRASE O METODO AGE DIFERENTE
					FRASE AGRADAVEL = ABANAR RABO E LATIR
					FRASE AGRESSIVA = ROSNAR
				DEPENDENDO DO HORARIO DO DIA
					MANHA = ABANAR - 6 - 12
					TARDE = ABANAR E LATIR - 12 - 18
					NOITE = IGNORAR - 18- 5
				DEPENDENDO DO DONO
					TRUE = ABANAR
					FALSE = ROSNAR E LATIR
				DE ACORDO COM IDADE E PESO
					NOVO E LEVE = ABANAR
					NOVO E PESADO = LATIR
					VELHO E LEVE = ROSNAR
					VELHO E PESADO = IGNORAR


			METODO REAGIR PODE OCORRER DE QUATRO MANEIRAS
				FAZER QUATRO METODOS COM MESMO NOME POREM COM PARAMETROS DIFRENTES
					1 = FRASE
						SE FRASE IGUAL OLA OU BOM GAROTO
							ESCREVE ABANAR RABO E LATIR
						SENAO
							ESCREVE ROSNAR - OU ROSNADO - OU RRRRRRRR
					2 = HORARIO DO DIA E MINUTO
						SE HORARIO MAIOR Q 18 E MENOR QUE 24
							ESCREVE IGNORAR
						SE HORARIO MAIOR QUE 12 E MENOR QUE 18
							ESCREVE ABANAR E LATIR
						SE HORARIO MAIOR QUE 6 E MENOR QUE 12
							ESCREVE ABANAR
						SE HORARIO MAIOR QUE 0 E MENOR QUE 6
							ESCREVE ZZZZZZZZZZZZ DORMINDO
						SENAO
							ESCREVE ERRO
					3 = DONO
							SE DONO TRUE
								ESCREVE ABANAR
							SENAO
								ESCREVE ROSNAR
					4 = IDADE E PESO
						SE IDADE MENOR QUE 12
							SE PESO MAIOR QUE 80
								ESCREVE LATIR
							SENAO
								ESCREVE ABANR
						SENAO
							SE PESO MAIOR QUE 80
								IGNORAR
							SENAO
								ROSNAR



*/						
