<?php 

interface IntCont
{
	public function ligar();
	public function desligar();
	public function abrirMenu();
	public function fecharMenu();
	public function mudo();
	public function tirarMudo();
	public function maisVol();
	public function menosVol();
	public function play();
	public function pause();
	public function canalMais();
	public function canalMenos();
	public function numCanal($x);
}

/*
/* EXERCICIO - ENCAPSULAMENTO
		
CRIAR ARQUIVO DA INTERFACE
COLOCAR DENTRO DA CLASSE
NO INDEX SOMENTE COLOCAR A CLASSE

INTERFACE
LIGAR
DESLIGAR
ABRIRMENU
FECHARMENU
MUDO
TIRARMUDO
MAISVOLUME
MENOSVOLUME
PLAY
PAUSE
CANALMAIS
CANALMENOS
NUMCANAL

CLASSE - CONTREMOTO

	//ATRIBUTOS
		VOLUME
		LIGADA
		TOCANDO
		CANAL
	//METODOS
		GET E SETTER
		CONSTRUCT
			VOLUME 50
			LIGADA FALSE
			TOCANDO FALSE
		SET VOLUME
			VAR = GETVOLUME + PARAMETRO
			SE VAR >= 100 OU VAR < 0
				ECHO ERRO
			ELSE
				VOLUME = VAR

	//METODOS INTERFACE
	LIGAR
		SE LIGADA == TRUE
			JA ESTA LIGADO
		ELSE
			LIGADA == TRUE
			CANAL = 1
	DESLIGAR
		SE LIGADA == TRUE
			LIGADA = FALSE
		ELSE
			JA DESLIGADO
	ABRIRMENU
		SE LIGADA == FALSE
			LIGUE PRIMEIRO
		ELSE
			ABRINDO MENU
			VOLUME
			CANAL
			TOCANDO
	FECHARMENU
		IF LIGADA == FALSE
			LIGUE PRIMEIRO
		ELSE
			FECHANDO MENU...
	MUDO
		IF LIGADO == FALSE
			LIGUE PRIMEIRO
		ELSE
			VOLUME = 0
			MOSTRAR ICONE DE MUDO
	TIRARMUDO
		IF LIGADO == FALSE
			LIGUE PRIMEIRO
		ELSE
			IF VOLUME == 0
				TIRANDO DO MUDO
				VOLUME = 50
			ELSE
				VOLUME NAO ESTÁ NO MUDO
	MAISVOLUME
		IF LIGADA == FALSE
			LIGUE PRIMEIRO
		ELSE
			VAR = VOLUME + 10
			ESCREVE VOLUME
			FOR I=1; I<=VOLUME; I++
				ESCREVE "I";
	MENOSVOLUME
		SVOLUME
		IF LIGADA == FALSE
			LIGUE PRIMEIRO
		ELSE
			VOLUME = VOLUME - 10
			ESCREVE VOLUME
			FOR I=1; I<=VOLUME; I++
				ESCREVE "I";
	PLAY
		IF LIGADA == FALSE
			LIGUE PRIMEIRO
		ELSE
			TOCANDO == TRUE
	PAUSE
		Y
		IF LIGADA == FALSE
			LIGUE PRIMEIRO
		ELSE
			TOCANDO == FALSE
			PAUSADO
	CANALMAIS
		IF LIGADA == FALSE
			LIGUE PRIMEIRO
		ELSE
			CANAL = CANAL + 1
			AGORA ESTA NO CANAL -> CANAL
	CANALMENOS
		IF LIGADA == FALSE
			LIGUE PRIMEIRO
		ELSE
			CANAL = CANAL - 1
			AGORA ESTA NO CANAL -> CANAL
	NUMCANAL(VALOR)
		IF LIGSADA == FALSE
			LIGUE PRIMEIRO
		ELSE
			CANAL = VALOR
			ESTA NO CANAL => CANAL
*/


?>